# Generated by Django 2.1.3 on 2018-11-09 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('cedula_id', models.AutoField(primary_key=True, serialize=False)),
                ('cedula', models.CharField(max_length=10)),
                ('codigo_matricula', models.CharField(max_length=8)),
                ('nombres', models.CharField(max_length=70)),
                ('apellidos', models.CharField(max_length=70)),
                ('carrera', models.CharField(choices=[('sistemas', 'Sistemas'), ('contabilidad', 'Contailidad'), ('forestal', 'Forestal'), ('medicina', 'Medicina'), ('ingles', 'Ingles')], max_length=15)),
                ('ciclo', models.CharField(choices=[('1', 'Primer Ciclo'), ('2', 'Primer Ciclo'), ('3', 'Primer Ciclo'), ('4', 'Primer Ciclo'), ('5', 'Primer Ciclo'), ('6', 'Primer Ciclo'), ('7', 'Primer Ciclo'), ('8', 'Primer Ciclo'), ('9', 'Primer Ciclo'), ('10', 'Primer Ciclo')], max_length=15)),
            ],
        ),
    ]
