# Generated by Django 2.1.3 on 2018-11-09 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelo', '0002_estudiante_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiante',
            name='ciclo',
            field=models.CharField(choices=[('1', 'Primer Ciclo'), ('2', 'Segundo Ciclo'), ('3', 'Tercer Ciclo'), ('4', 'Cuarto Ciclo'), ('5', 'Quinto Ciclo'), ('6', 'Sexto Ciclo'), ('7', 'Septimo Ciclo'), ('8', 'Octavo Ciclo'), ('9', 'Noveno Ciclo'), ('10', 'Decimo Ciclo')], max_length=15),
        ),
    ]
